### PR TITLE
Animation and transition pull request

### PR DESCRIPTION
**Pull request by codecaiine**
- I created a new branch
- I added animation and transition to my project.
- I fixed linters errors
- I updated my media queries for the mobile side
- I tested the different versions on different devices
- I added mobile version media query 
**This is my second Request Review, feel free to contact me on slack [Yannick-Noel] if anything's wrong**

### CODE REVIEW

**Comment by o-rashad** [comment]
Hey @codecaiine ,

Unfortunately, I have mistakenly invalidated your PR.
Please don't worry about it, the Dev team is working to solve the issue.

Thank you.

**Comment by o-rashad** [comment]
Meantime, submit another CR. so you don't get delayed. @codecaiine

**Comment by codecaiine** [comment]
Thank you !!

**Review by vichuge — CHANGES_REQUESTED** [review]
# Required Changes ♻️ ⚠️ 🚦 

Hi dear student, 

Good job so far!
You still need to work on some issues to go to the next project, but you are almost there!

mario_ladders

## Good points 👍 
You used proper GitHub Flow ✔️
Your linter checks are all passing ✔️
Your README and PR message are descriptive ✔️

## Aspects to improve ♻️

- [ ] I kindly invite you to check your project on mobile size, using google chrome with dev tools on galaxy 5 size, I could observe these bugs:
image
image

- Please, focus on the deployment mobile size too. 🐶 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by codecaiine** [comment]
Hello @vichuge 
Thank you for your review and comment. I update my code.  Please see below my work. It workin.g fine from my laptop 

Galaxy1
Galaxy
galaxy3
Galaxy2

**Comment by codecaiine** [comment]
You can check from mobile 
Screenshot_20210727-181527_Chrome
Screenshot_20210727-181511_Chrome
Screenshot_20210727-180644_Chrome

**Review by claudinenic — APPROVED** [review]
## STATUS: APPROVED :muscle::clap:

Hi, @codecaiine 

Congratulations! :tada:
Your project is complete!  It's time to merge it :shipit:
Great work on implementing the changes requested by the previous TSEs
  
Cheers and Happy coding! :clap: :clap: :clap:

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

#### _**Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.**_
------------------------------------------------------------------------------------------------------------------------------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using this [form.](https://airtable.com/shrQAqnBwek5a0O0s)

**Pull request merged**
